### ISSUE TITLE
make: *** [all] Error 2

### ISSUE THREAD

**Issue by Klairm** [wargio/ps3soundlib#1]
/opt/ps3dev/psl1ght/base_rules:68: recipe for target 'main.o' failed
make[2]: *** [main.o] Error 1
Makefile:115: recipe for target 'build' failed
make[1]: *** [build] Error 2
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wargio** [comment]
Thats weird. Which version of psl1ght are you using?

**Comment by Klairm** [comment]
https://github.com/HACKERCHANNEL/PSL1GHT

**Comment by wargio** [comment]
you cannot build it with that. you need PSL1GHT v2

**Comment by wargio** [comment]
https://github.com/ps3dev/PSL1GHT
